### ISSUE TITLE
Scale/range of the cost layer

### ISSUE THREAD

**Issue by mim25** [pierreroudier/clhs#14]
Hello,
Apologies if this is simplistic.

What is the scale/range of the cost layer? 0-100, 0-10, -100 -100, weighted etc. ?
and
Can negative scores be used i.e. to define preferred sites.

Thanks in advance

**Comment by dylanbeaudette** [comment]
I'm not sure, but in the past I have used weights of 0, or near-0, for "easily accessed" parts of the landscape such as roads and improved trails.

**Comment by pierreroudier** [comment]
I does not matter, because the algorithm is simply trying to minimise that cost. 

Following a great idea from @dylanbeaudette back in the days, I have mostly designed it to be used with a cost layer derived from eg [GRASS GIS's r.walk](https://grass.osgeo.org/grass78/manuals/r.walk.html). 

Negative scores could be used, although like @dylanbeaudette I tend to just flag them as zero.

Please do re-open the issue if you spot a behaviour that is inconsistent with these notes.
